BEGIN;

CREATE TABLE accounts (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance numeric(1000, 2) CHECK (balance >= 0)
);

CREATE TABLE transaction_history (
    id_from int,
    id_to int,
    amount numeric(1000, 2),
    comment text,
    created_at timestamp
);

END;